# Generated by Django 5.0.1 on 2024-01-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailUser',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nameUser',
        ),
    ]
