# Generated by Django 5.0.1 on 2024-01-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_email_user_emailuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRDV', models.DateField()),
                ('heureRDV', models.TimeField()),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
