# Generated by Django 5.0.1 on 2024-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='phoneNumber',
            field=models.IntegerField(default='0518142560', null=True),
        ),
    ]
