# Generated by Django 5.0.1 on 2024-01-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lawyer_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('clientRating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('lawyerRating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyer')),
            ],
        ),
    ]
